---
- hosts: servers
  vars_files:
    - vars.yml
  gather_facts: false
  sudo: true

  tasks:
  - name: Create the project directory.
    file: state=directory path={{ project_root }}

  - name: Create user.
    user: home={{ project_root }}/home/ name={{ project_name }} state=present

  - name: Update the project directory.
    file: group={{ project_name }} owner={{ project_name }} mode=755 state=directory path={{ project_root }}

  - name: Create the code directory.
    file: group={{ project_name }} owner={{ project_name }} mode=755 state=directory path={{ project_root }}/code/

  - name: Install required system packages.
    apt: pkg={{ item }} state=installed update-cache=yes
    with_items: "{{ system_packages }}"

  - name: Install required Python packages.
    easy_install: name={{ item }}
    with_items: "{{ python_packages }}"

  - name: Create the SSH directory.
    file: state=directory path={{ project_root }}/home/.ssh/

  - name: Upload SSH known hosts.
    copy: src=known_hosts dest={{ project_root }}/home/.ssh/known_hosts mode=0600

  - name: Upload SSH key.
    copy: src=key dest={{ project_root }}/home/.ssh/id_rsa mode=0600

  - name: Change permissions.
    shell: chown -R {{ project_name }}:{{ project_name }} {{ project_root }}

  - name: Install nginx configuration file.
    copy: src=files/conf/nginx.conf dest=/etc/nginx/sites-enabled/{{ project_name }}
    notify: restart nginx

  - name: Install init scripts.
    copy: src=files/init/{{ item }}.conf dest=/etc/init/{{ item }}.conf
    with_items: "{{ initfiles }}"

  - name: Install pg_hba.conf.
    copy: src=files/conf/pg_hba.conf dest=/etc/postgresql/9.3/main/pg_hba.conf
    notify: restart postgresql

  - name: Install npmrc.
    copy: src=files/conf/npmrc dest={{ project_root }}/home/.npmrc

  - name: Create database.
    shell: "sudo -u postgres createdb -T template_postgis mozio"
    ignore_errors: yes

  - name: Create database user.
    shell: "sudo -u postgres createuser -d mozio"
    ignore_errors: yes

  handlers:
    - include: handlers.yml

- include: deploy.yml

- hosts: servers
  vars_files:
    - vars.yml
  gather_facts: false
  sudo: true

  tasks:
  - name: Restart services.
    service: name={{ project_name }} state=restarted

